spring.application.name=08.sb-ai-app-advisors

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.model=gpt-4o
#spring.ai.openai.chat.max-tokens=200
#logging.level.root=debug

logging.level.org.springframework.ai.chat.client.advisor=DEBUG