server:
  port: 8080
spring:
  application:
    name: 06.spring-ai-vector-rag
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        model: gpt-4o
        max-tokens: 1000
      embedding:
        model: text-embedding-3-small
        dimensions: 512
    vectorstore:
      pinecone:
        api-key: <vector_key>