spring.application.name=01.sb-ai-app

spring.ai.openai.api-key=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
spring.ai.openai.chat.model=gpt-4o
spring.ai.openai.chat.max-tokens=100

logging.level.org.springframework.ai.chat.client.advisor=DEBUG