spring.application.name=19.spring-ai-vector-rag

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.model=gpt-4o

spring.ai.openai.embedding.model=text-embedding-3-small
spring.ai.openai.embedding.dimensions=512

spring.ai.vectorstore.pinecone.api-key=${PINECONE_API_KEY}
spring.ai.vectorstore.pinecone.index-name=cgspringaidb
