spring.application.name=16.spring-ai-tools-calling-time

spring.ai.openai.api-key= ${OPENAI_API_KEY}
spring.ai.openai.chat.model= gpt-4o
spring.ai.openai.chat.max-tokens= 100

logging.level.org.springframework.ai.chat.client.advisor.log=debug