spring.application.name=15.spring-ai-streaming

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.model=gpt-4o

logging.level.org.springframework.ai=INFO
logging.level.reactor.netty.http.client=WARN
spring.ai.chat.client.observations.log-prompt=true
spring.ai.chat.client.observations.log-completion=true

logging.file.name=logs/stream-app.log