spring.application.name=17.spring-ai-tool-calling-web-search

spring.ai.openai.api-key= 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
spring.ai.openai.chat.model= gpt-4o
spring.ai.openai.chat.max-tokens= 100

web-search.apiKey=${TAVILY_API_KEY}
web-search.baseUrl: https://api.tavily.com
web-search.defaultMaxResults: 5