spring.application.name=18.spring-ai-mcp-client

spring.ai.openai.api-key=${OPENAI_API_KEY}
#spring.ai.openai.chat.max-tokens=100

spring.ai.mcp.client.stdio.servers-configuration=classpath:mcp-servers.json