spring.application.name=15.spring-ai-streaming

spring.ai.ollama.chat.model=gemma:2b

logging.level.org.springframework.ai=INFO
logging.level.reactor.netty.http.client=WARN
spring.ai.chat.client.observations.log-prompt=true
spring.ai.chat.client.observations.log-completion=true

logging.file.name=logs/stream-app.log